import { useEffect, useState } from "react";
import { Button } from "@heroui/button";
import { Card, CardBody, CardHeader } from "@heroui/card";
import { Input } from "@heroui/input";
import { Select, SelectItem } from "@heroui/select";
import { Switch } from "@heroui/switch";
import toast from "react-hot-toast";
import { adjustAdminSubscriptionUser, completeAdminTestOrder, createAdminPlan, deleteAdminPlan, generateRedeemCodes, getAdminPaymentOrders, getAdminPlans, getAdminRedeemCodes, getAdminSubscriptionAudit, getAdminSubscriptionUser, resetAdminSubscriptionQuota, retryAdminPaymentOrder, revokeRedeemCode, updateAdminPlan } from "@/api";

const empty = { name: "", description: "", price: "0", currency: "CNY", validityValue: "1", validityUnit: "month", trafficGb: "0", resetDay: "1", resetQuota: true, maxForwards: "0", forSale: true, redeemable: true, status: true, sortOrder: "0" };
const payload = (f: typeof empty) => ({ ...f, price: Number(f.price), validityValue: Number(f.validityValue), trafficBytes: Math.round(Number(f.trafficGb) * 1073741824), resetDay: Number(f.resetDay), resetQuota: f.resetQuota ? 1 : 0, maxForwards: Number(f.maxForwards), sortOrder: Number(f.sortOrder), forSale: f.forSale ? 1 : 0, redeemable: f.redeemable ? 1 : 0, status: f.status ? 1 : 0 });
const bytes = (n: number) => n ? `${(n / 1073741824).toFixed(2)} GB` : "不限";
const validity = (p: any) => p.validityUnit === "permanent" ? "永久" : `${p.validityValue}${p.validityUnit === "year" ? "年" : "个月"}`;

export default function AdminSubscriptionPage() {
  const [plans, setPlans] = useState<any[]>([]), [codes, setCodes] = useState<any[]>([]), [orders, setOrders] = useState<any[]>([]), [form, setForm] = useState(empty), [editing, setEditing] = useState<number | null>(null), [selected, setSelected] = useState(""), [count, setCount] = useState("10"), [generated, setGenerated] = useState(""), [userId, setUserId] = useState(""), [subscription, setSubscription] = useState<any>(null), [audit, setAudit] = useState<any[]>([]);
  const load = async () => { const [a,b,c] = await Promise.all([getAdminPlans(), getAdminRedeemCodes(), getAdminPaymentOrders()]); if (a.code === 0) setPlans(a.data || []); if (b.code === 0) setCodes(b.data || []); if (c.code === 0) setOrders(c.data || []); };
  useEffect(() => { load(); }, []);
  const set = (k: keyof typeof empty, v: any) => setForm(x => ({ ...x, [k]: v }));
  const save = async () => { const r = editing ? await updateAdminPlan(editing, payload(form)) : await createAdminPlan(payload(form)); if (r.code === 0) { toast.success(editing ? "套餐已更新" : "套餐已创建"); setEditing(null); setForm(empty); load(); } else toast.error(r.msg || "保存失败"); };
  const edit = (p: any) => { setEditing(p.id); setForm({ name:p.name||"", description:p.description||"", price:String(p.price||0), currency:p.currency||"CNY", validityValue:String(p.validityValue||1), validityUnit:p.validityUnit||"month", trafficGb:String(p.trafficBytes ? (p.trafficBytes / 1073741824) : 0), resetDay:String(p.resetDay ?? 1), resetQuota:p.resetQuota !== 0, maxForwards:String(p.maxForwards||0), forSale:p.forSale===1, redeemable:p.redeemable===1, status:p.status===1, sortOrder:String(p.sortOrder||0) }); };
  const makeCodes = async () => { if (!selected) return toast.error("请选择套餐"); const r = await generateRedeemCodes(Number(selected), Math.min(1000, Math.max(1, Number(count)||1))); if (r.code === 0) { setGenerated((r.data||[]).join("\n")); toast.success("兑换码已生成"); load(); } else toast.error(r.msg || "生成失败"); };
  const findSubscription = async () => { const [r, logs] = await Promise.all([getAdminSubscriptionUser(Number(userId)), getAdminSubscriptionAudit(Number(userId))]); if (r.code === 0 && r.data) setSubscription(r.data); else { setSubscription(null); toast.error(r.msg || "未找到套餐"); } if (logs.code === 0) setAudit(logs.data || []); };
  return <div className="p-4 space-y-4 max-w-6xl"><div><h1 className="text-xl font-bold">套餐与兑换码管理</h1><p className="text-sm text-default-500">套餐额度按账号共享，明文兑换码仅在生成时展示。</p></div>
    <Card><CardHeader><b>{editing ? "编辑套餐" : "新建套餐"}</b></CardHeader><CardBody className="grid md:grid-cols-4 gap-3"><Input label="名称" value={form.name} onChange={e=>set("name",e.target.value)}/><Input label="描述" value={form.description} onChange={e=>set("description",e.target.value)}/><Input label="价格" type="number" value={form.price} onChange={e=>set("price",e.target.value)}/><Input label="货币" value={form.currency} onChange={e=>set("currency",e.target.value)}/><Input label="有效期数值" type="number" value={form.validityValue} isDisabled={form.validityUnit==="permanent"} onChange={e=>set("validityValue",e.target.value)}/><Select label="有效期单位" selectedKeys={[form.validityUnit]} onSelectionChange={k=>set("validityUnit",String(Array.from(k)[0]||"month"))}><SelectItem key="month">月</SelectItem><SelectItem key="year">年</SelectItem><SelectItem key="permanent">永久/不限制时间</SelectItem></Select><Input label="流量上限（GB，0=不限）" type="number" value={form.trafficGb} onChange={e=>set("trafficGb",e.target.value)}/><Input label="重置日（1-31，0=不重置）" type="number" value={form.resetDay} onChange={e=>set("resetDay",e.target.value)}/><Switch isSelected={form.resetQuota} onValueChange={v=>set("resetQuota",v)}>每月恢复完整流量</Switch><Input label="转发上限(0=不限)" type="number" value={form.maxForwards} onChange={e=>set("maxForwards",e.target.value)}/><Switch isSelected={form.forSale} onValueChange={v=>set("forSale",v)}>允许购买</Switch><Switch isSelected={form.redeemable} onValueChange={v=>set("redeemable",v)}>允许兑换</Switch><Switch isSelected={form.status} onValueChange={v=>set("status",v)}>启用</Switch><div className="flex gap-2"><Button color="primary" onPress={save}>{editing?"保存":"创建"}</Button>{editing&&<Button variant="flat" onPress={()=>{setEditing(null);setForm(empty)}}>取消</Button>}</div></CardBody></Card>
    <div className="grid md:grid-cols-3 gap-3">{plans.map(p=><Card key={p.id}><CardHeader className="justify-between"><b>{p.name}</b><span>{p.price} {p.currency}</span></CardHeader><CardBody className="text-sm space-y-2"><div>{validity(p)} · {bytes(p.trafficBytes)} · {p.resetQuota===0?"有效期内总量不恢复":"每月恢复完整流量"} · 转发 {p.maxForwards||"不限"}</div><div>{p.status===1?"启用":"停用"} / {p.forSale===1?"可购买":"不可购买"}</div><div className="flex gap-2"><Button size="sm" onPress={()=>edit(p)}>编辑</Button><Button size="sm" color="danger" variant="flat" onPress={async()=>{if(!window.confirm("停用套餐？"))return;const r=await deleteAdminPlan(p.id);if(r.code===0){toast.success("套餐已停用");load()}else toast.error(r.msg)}}>停用</Button></div></CardBody></Card>)}</div>
    <Card><CardHeader><b>批量兑换码</b></CardHeader><CardBody className="space-y-3"><div className="grid md:grid-cols-3 gap-3"><Select label="套餐" selectedKeys={selected?[selected]:[]} onSelectionChange={k=>setSelected(String(Array.from(k)[0]||""))}>{plans.filter(p=>p.status===1&&p.redeemable===1).map(p=><SelectItem key={p.id}>{p.name}</SelectItem>)}</Select><Input label="数量（最多 1000）" type="number" value={count} onChange={e=>setCount(e.target.value)}/><Button className="self-end" color="primary" onPress={makeCodes}>生成</Button></div>{generated&&<pre className="max-h-48 overflow-auto rounded bg-default-100 p-3 text-sm whitespace-pre-wrap">{generated}</pre>}<div className="max-h-56 overflow-auto text-sm"><table className="w-full"><thead><tr className="text-left"><th>前缀</th><th>套餐</th><th>批次</th><th>状态</th><th/></tr></thead><tbody>{codes.map(c=><tr className="border-t border-divider" key={c.id}><td>{c.codePreview}</td><td>{plans.find(p=>p.id===c.planId)?.name||c.planId}</td><td>{c.batchId||"-"}</td><td>{c.status===1?"可用":c.status===0?"已使用":"已作废"}</td><td>{c.status===1&&<Button size="sm" color="danger" variant="light" onPress={async()=>{const r=await revokeRedeemCode(c.id);if(r.code===0){toast.success("已作废");load()}else toast.error(r.msg)}}>作废</Button>}</td></tr>)}</tbody></table></div></CardBody></Card>
    <div className="grid lg:grid-cols-2 gap-3"><Card><CardHeader><b>用户套餐配额</b></CardHeader><CardBody className="space-y-3"><div className="flex gap-2"><Input label="用户 ID" value={userId} onChange={e=>setUserId(e.target.value)}/><Button className="self-end" onPress={findSubscription}>查询</Button></div>{subscription&&<div className="text-sm space-y-2"><div>套餐：{plans.find(p=>p.id===subscription.planId)?.name||subscription.planId}</div><div>到期：{new Date(subscription.expiresAt).toLocaleString()}</div><div>已用：{bytes(subscription.trafficUsedBytes)} / {bytes(subscription.trafficLimitBytes)}</div><div className="flex gap-2"><Button size="sm" onPress={async()=>{const r=await resetAdminSubscriptionQuota(Number(userId));if(r.code===0){setSubscription(r.data);toast.success("已重置")}}}>重置流量</Button><Button size="sm" color={subscription.status===1?"danger":"success"} onPress={async()=>{const r=await adjustAdminSubscriptionUser(Number(userId),{status:subscription.status===1?0:1});if(r.code===0){setSubscription(r.data);toast.success("已调整")}}}>{subscription.status===1?"停用套餐":"启用套餐"}</Button></div><div className="pt-2"><div className="font-medium">套餐审计</div><div className="max-h-28 overflow-auto text-xs">{audit.length ? audit.map(item=><div className="border-t border-divider py-1" key={item.id}>{new Date(item.createdTime).toLocaleString()} · {item.eventType}{item.amount ? ` · ${bytes(item.amount)}` : ""}</div>) : <div className="text-default-400">暂无记录</div>}</div></div></div>}</CardBody></Card><Card><CardHeader><b>支付订单</b></CardHeader><CardBody><div className="max-h-56 overflow-auto text-sm"><table className="w-full"><thead><tr className="text-left"><th>订单号</th><th>渠道</th><th>金额</th><th>状态</th><th/></tr></thead><tbody>{orders.map(o=><tr className="border-t border-divider" key={o.id}><td>{o.orderNo}</td><td>{o.provider}</td><td>{o.amount} {o.currency}</td><td>{o.status}</td><td>{o.status!=="paid"&&<div className="flex gap-1"><Button size="sm" variant="light" onPress={async()=>{const r=await retryAdminPaymentOrder(o.orderNo);if(r.code===0)toast.success("支付指令已重新生成");else toast.error(r.msg||"重试失败")}}>重试</Button><Button size="sm" variant="light" onPress={async()=>{const r=await completeAdminTestOrder(o.orderNo);if(r.code===0){toast.success("测试订单已完成");load()}else toast.error(r.msg||"无法完成")}}>测试完成</Button></div>}</td></tr>)}</tbody></table></div></CardBody></Card></div>
  </div>;
}
